### ISSUE TITLE
Config options?

### ISSUE THREAD

**Issue by oemsysadm** [fthx/panel-free#1]
I love the super simple extension, thank you for making this for those of us missing our panel hiding extensions in v45.

One minor thing, would it be possible to add a config option to disable the activities overview popping up when moving the mouse below the bottom of the screen? I've had it do this several times on accident, and I generally prefer to use the super key for more predictably going in and out of the overview.

I could also imagine some people would like to be able to choose the edge/corner that brings the overview up, rather than disable this functionality.

**Comment by fthx** [comment]
Hi, I won't make prefs for this one.
And I won't remove the bottom trigger.
You can simply comment out these 3 lines:
![image](https://github.com/fthx/panel-free/assets/23138504/351f8aee-182b-4ba5-98f8-3ff0a9a719db)

**Comment by fthx** [comment]
https://github.com/fthx/panel-free/commit/8621616b2120843dc15a3f704a1465f17f94141f
