### ISSUE TITLE
Hot Corner 

### ISSUE THREAD

**Issue by tibuski** [fthx/panel-free#2]
Hello,

Thank you for the extension !

I was wondering if it would be possible to keep the Hot Corner feature with this extension enabled ?

Kind Regards,

Laurent

**Comment by fthx** [comment]
Nope.
Hiding the panel is a very simple solution but removes hot corner access.
Here I won't solve this (I did it in the past, just showing 1 px height of the panel).
I suggest to use Bottom Overview extension (works with Panel Free after the first overview).

**Comment by fthx** [comment]
My opinion is that hot corner is a very outdated way to expose overview.
In older GS it was good since the dash was left positioned.
Now it's imo useless because the dash is bottom positioned.

**Comment by tibuski** [comment]
Thank you for your quick and complete answer !

FYI, I use your extension to have a fully empty screen and press the Super key to start anything (I have no Dash).

Moving the mouse in the corner would allow to either user keyboard or mouse.
I'll check if I can add a one pixel in upper left corner that could do the trick.

Thank you again for your work !

**Comment by fthx** [comment]
Just have to:
Main.panel.set_height(1)
instead of:
Main.panel.hide()

**Comment by fthx** [comment]
(you will need to store the old height first, but let's see if it fills your needs)

**Comment by tibuski** [comment]
it's working as expected but indeed it doesn't show back as it keeps being 1 px :)
You were already really helpful, I don't want to take too much of your time !

**Comment by fthx** [comment]
Try the latest version: panel is now reduced to 0 height because hiding causes some (harmless) error messages.
You can now access hidden panel elements bu clicking on them!
Could you tell me if hot corner is now still alive?

**Comment by fthx** [comment]
If not, keep doing height = 1 in code.

**Comment by tibuski** [comment]
I played with 1Px on a copy of your code and it woks as expected except, to be clean, I need to find how to hide or reduce the size of the new Activity (WorkspaceIndicator).

I'll try your new code !

**Comment by tibuski** [comment]
With your new code, hot cornet don't work and I have the same issue on the top left corner :

![Screenshot from 2023-11-22 14-43-37](https://github.com/fthx/panel-free/assets/36230291/53aa00a2-a066-4f75-9084-c70385c03d62)

**Comment by fthx** [comment]
Yes I get it too, I don't know why it's still visible.

**Comment by tibuski** [comment]
I was looking if I could hide it but then I had to go back to work :)
I will come back here if I find a solution.
